Add Douglas Park pic
MLH-Fellowship/batch-2-map pull request #96
Opened 2021-04-16 17:44 UTC by dogurasu

## Please, go through these steps before you submit a PR.

- [ ] Make sure your photo is an exact square.
- [ ] Make sure the photo is named {firstname-lastname-podnumber}.{jpg or png}.
- [ ] Make sure the photo is in the correct directory.

2021-04-16 18:58 UTC, wrussell1999 requested changes
Hey @dogurasu, can you make this a square?

2021-04-16 20:20 UTC, dogurasu commented
> Hey @dogurasu, can you make this a square?

Is this better?

2021-04-19 08:03 UTC, wrussell1999 commented
Can you remove the old photo from your PR?

2021-04-19 08:30 UTC, wrussell1999 approved these changes

2021-04-19 08:30 UTC, merged